### ISSUE TITLE
Error when running susi 

### ISSUE THREAD

**Issue by yisraelgrimes** [AVGP/susi#9]
I know it's been a while since this project's seen any action but... It's so simple and elegant I'm hoping you can help me out. When running the susi command as per the readme, I'm getting an error. For testing, I've just been using your example html and markdown so I don't think that would be the issue. Here's the error message:
```
Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:634:3)
    at tryReadSync (fs.js:474:20)
    at Object.fs.readFileSync (fs.js:515:19)
    at convertFilesInPath (/usr/local/lib/node_modules/susi/susi:43:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/susi/susi:62:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
```

Any help that you could give me would be very much appreciated :) 

Thanks!

**Comment by jeremykohn** [comment]
Found the issue:

The version of susi from NPM (0.1.4) expects the third argument to be an HTML file, e.g. `/var/www/layout.html`, not a directory which ends in a slash.

The GitHub repo has a newer version of susi (0.2.3), which [expects the third argument to have a trailing slash](https://github.com/AVGP/susi/blob/master/susi#L11). However, I haven't yet installed and tested this version.

**Comment by jeremykohn** [comment]
Just tested and confirmed: in version 0.2.3, each of the three arguments must be a directory, not a file.
```
susi directory/with/markdown_files/ output_directory/ path/to/layouts/
```
And as it turns out, each trailing slash is optional.
